Fix issue when SSHAgentConnector doesn't have right libraries.
java.lang.NoClassDefFoundError: Could not initialize class
com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary